# Generated by Django 2.2.1 on 2019-05-18 09:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.get_image_path),
        ),
    ]
